title: Davíð's site
author: Davíð Freyr Björnsson
email: david24099@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Portfolio site and blog about Data Science.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Davíð Freyr Björnsson
  tagline: Master's student in Data Science.
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    github: dfb2
    linkedIn: in/davíð-freyr-björnsson-0b950870

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
